apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-product
  template:
    metadata:
      labels:
        app: mall-product
    spec:
      containers:
        - name: mall-product
          image: 171312460935.dkr.ecr.ap-southeast-1.amazonaws.com/mall-product:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mall-product-service
spec:
  selector:
    app: mall-product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
